#!/bin/sh
#
# makesrcdist - make a source distribution of mantohtml.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating mantohtml-$version.tar.gz...
git archive --format tar --prefix=mantohtml-$version/ HEAD | gzip -v9 >mantohtml-$version.tar.gz
gpg --detach-sign mantohtml-$version.tar.gz

